# Site settings
title:          Vox Nihili
description:    "A bilingual co-production in the form of a blog maintained by some students."
baseurl:        ""
url:            "https://voxnihi.li"

plugins:
  - jekyll-sitemap

# Author
author:
  name:         Vox Nihili
  url:          https://voxnihi.li
  email:        

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:title
paginate:       7
